services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant:/root/.qdrant
    ports:
      - "6333:6333"
      - "6334:6334"

volumes:
  ollama:
  qdrant:
